import { useSession } from "next-auth/react";
import Head from "next/head";
import React, { useEffect } from "react";
import Nav from "../nav";

const Layout = ({ children }: { children: React.ReactNode }) => {
    const session = useSession();
    useEffect(() => {
        console.log(session);
    }, [session]);
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Nav status={session.status} name={session.data?.user?.name} image={session.data?.user?.image} />
            <main className="container overflow-y-scroll overflow-x-hidden mx-auto  flex flex-col items-center justify-center p-1 small:p-4 h-screen">{children}</main>
        </>
    );
};

export default Layout;
